### ISSUE TITLE
How to handle large data more then 1000000

### ISSUE THREAD

**Issue by neerajchourasia** [mustafasaifee42/VR-Viz#16]
Hi Team,

I am trying this library to plot different graphs for data that is in .CSV file and containing more than 1000000 records.
This library is not able to handle this much data, app getting crash. I am able to run the app by using 100000 records. 
My requirement is to load more than 1000000 records over the graph and charts.

Can you please help me regards this?

Thank you so much in advance.

**Comment by mustafasaifee42** [comment]
@neerajchourasia Can you let me know which graph are you trying to use and does your computer have a dedicated graphics card?

**Comment by neerajchourasia** [comment]
@mustafasaifee42 I am using MacBook Pro here is configuration

Processor : 2.6 GHz Intel Core i7
Memory : 16 GB 2400 MHz DDR4
Graphics : Radeon Pro 560X 4 GB Intel UHD Graphics 630 1536 MB

I am using following graphs :- 
vr-viz-Scatter Plot
vr-viz-Scatter Plot Connected
vr-viz-Scatter Plot Droplines
vr-viz-Scatter Plot Projection

Running this as react project using NPM RUN START command.

**Comment by mustafasaifee42** [comment]
Have you tried using box instead of sphere as its take more computational power to visualize data? If possible can you share your data sheet via email (saifee.mustafa@gmail.com)

**Comment by mustafasaifee42** [comment]
@neerajchourasia did it work for you?

**Comment by neerajchourasia** [comment]
@mustafasaifee42 it is not working.

**Comment by neerajchourasia** [comment]
@mustafasaifee42 Is there are any limits in number of rows imposed by the library?

**Comment by neerajchourasia** [comment]
@mustafasaifee42  How can I use box instead of sphere?

**Comment by neerajchourasia** [comment]
I have sent file over mail and shared github link as well.

**Comment by neerajchourasia** [comment]
@mustafasaifee42 Did you get a chance to look into this issue, please help to resolve this issue or suggest me to alternate way to implement.

**Comment by mustafasaifee42** [comment]
I have added a feature to visualize millions of data point: https://github.com/mustafasaifee42/VR-Viz#optimizeview-bool

**Comment by mustafasaifee42** [comment]
Closing this issue now
