### ISSUE TITLE
rotate labels to always face hmd camera

### ISSUE THREAD

**Issue by micahstubbs** [mustafasaifee42/VR-Viz#3]
rotate labels to always face hmd camera
 
## user story

as a user, I want to be able to easily read axis tick label text and mark label text from any position or perspective

## screenshot

![vr-viz-labels-1](https://user-images.githubusercontent.com/2119400/42183786-f9219838-7df7-11e8-9e29-806a6963ff2d.png)

**Comment by mustafasaifee42** [comment]
Added billboarding feature to all the text element i.e. the ticks and labels.

![image](https://user-images.githubusercontent.com/29223820/56824759-0c0f7700-6860-11e9-9f43-2f448523f1ca.png)

**Comment by micahstubbs** [comment]
@mustafasaifee42 nice work!  cool to see this one go in 😄 🙌
