### ISSUE TITLE
Cannot enter VR mode in Windows MR Headset

### ISSUE THREAD

**Issue by dirkk0** [mustafasaifee42/VR-Viz#7]
Hi,

  first of all - thanks for this library!

I suspect I am doing something wrong, but I cannot enter VR mode on my Windows MR headset. It works ok on an Oculus Quest, albeit quite slow.
It's simply that the VR icon in the bottom right corner of the demo iFrame on doesn't show up.
Any ideas?

Thanks,
  Dirk

Edit: I am in the cliff house, standing in front of a Edge Browser window; other A-Frame examples work.

**Comment by mustafasaifee42** [comment]
When using iframes, iframe with **allowfullscreen="yes"** and **allowvr="yes"** like **<iframe allowvr="yes" allowfullscreen="yes" src="www.example.com" />**. 

Documentation for a-frame in iframe is [here](https://aframe.io/docs/0.9.0/components/embedded.html).

**Comment by mustafasaifee42** [comment]
Closing this issue
